service: gotest

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

package:
  artifact: handler.zip


functions:

  plain:
    handler: handler.HandlePlain
    environment:
      apiBaseUrl: { "Fn::Join" : ["", [" https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}" ] ]  }

  get:
    handler: handler.Handle
    events:
    - http:
        path: test/{id}
        method: get
        request:
          parameters:
            paths:
              id: true