service: gotest

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1

package:
  artifact: handler.zip


functions:

  plain:
    handler: handler.HandlePlain

  get:
    handler: handler.Handle
    events:
    - http:
        path: test/{id}
        method: get
        request:
          parameters:
            paths:
              id: true